name: Assign PRs to their respective authors

on:
    pull_request:
        types:
            - opened

permissions:
    pull-requests: write

jobs:
    assign-pr:
        runs-on: ubuntu-slim

        steps:
            - run: gh pr edit $PR_ID --add-assignee $USER
              env:
                  GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  PR_ID: ${{ github.event.pull_request.number }}
                  USER: ${{ github.event.pull_request.user.login }}
